/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.OWSB.ADMIN;

import com.mycompany.OWSB.FINANCE.Finance_Dashboard;
import com.mycompany.OWSB.INVENTORY.Inventory_Dashboard;
import com.mycompany.OWSB.PURCHASE.Purchase_Dashboard;
import com.mycompany.OWSB.SALES.Sales_Dashboard;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author cindy
 */
public class Admin_Others extends javax.swing.JPanel {
    private javax.swing.JPanel ChangePanel;

    /**
     * Creates new form Admin_Others
     */
    public Admin_Others(javax.swing.JPanel ChangePanel) {
        this.ChangePanel = ChangePanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SM_Button = new javax.swing.JButton();
        PM_Button = new javax.swing.JButton();
        IM_Button = new javax.swing.JButton();
        FM_Button = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Other Functions");

        SM_Button.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        SM_Button.setText("<html>Sales<br> Manager<html>");
        SM_Button.setToolTipText("");
        SM_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SM_ButtonActionPerformed(evt);
            }
        });

        PM_Button.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        PM_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Purchase_Manager.png"))); // NOI18N
        PM_Button.setText("<html>Purchase<br> Manager<html>");
        PM_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PM_ButtonActionPerformed(evt);
            }
        });

        IM_Button.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        IM_Button.setText("<html>Inventory<br> Manager<html>");
        IM_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IM_ButtonActionPerformed(evt);
            }
        });

        FM_Button.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        FM_Button.setText("<html>Finance<br> Manager<html>");
        FM_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FM_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SM_Button)
                            .addComponent(IM_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PM_Button)
                            .addComponent(FM_Button)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PM_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SM_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IM_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FM_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PM_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PM_ButtonActionPerformed
        // TODO add your handling code here:
        // Get the current Admin Dashboard JFrame
        JFrame adminFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

        // Create and show the Purchase Dashboard
        Purchase_Dashboard pd = new Purchase_Dashboard();

        // Set close operation to dispose, not exit
        pd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Hide the admin dashboard
        adminFrame.setVisible(false);

        // Re-show admin dashboard when Purchase Dashboard is closed
        pd.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                adminFrame.setVisible(true);
            }

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                adminFrame.setVisible(true);
            }
        });

        pd.setVisible(true);
    }//GEN-LAST:event_PM_ButtonActionPerformed

    private void SM_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SM_ButtonActionPerformed
        // TODO add your handling code here:
        JFrame adminFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        Sales_Dashboard pd = new Sales_Dashboard();
        pd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        adminFrame.setVisible(false);
        
        pd.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                adminFrame.setVisible(true);
            }

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                adminFrame.setVisible(true);
            }
        });

        pd.setVisible(true);
    }//GEN-LAST:event_SM_ButtonActionPerformed

    private void FM_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FM_ButtonActionPerformed
        // TODO add your handling code here:
        JFrame adminFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        Finance_Dashboard pd = new Finance_Dashboard();
        pd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        adminFrame.setVisible(false);
        
        pd.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                adminFrame.setVisible(true);
            }

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                adminFrame.setVisible(true);
            }
        });

        pd.setVisible(true);
    }//GEN-LAST:event_FM_ButtonActionPerformed

    private void IM_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IM_ButtonActionPerformed
        // TODO add your handling code here:
        JFrame adminFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        Inventory_Dashboard pd = new Inventory_Dashboard();
        pd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        adminFrame.setVisible(false);
        
        pd.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                adminFrame.setVisible(true);
            }

            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                adminFrame.setVisible(true);
            }
        });

        pd.setVisible(true);
    }//GEN-LAST:event_IM_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FM_Button;
    private javax.swing.JButton IM_Button;
    private javax.swing.JButton PM_Button;
    private javax.swing.JButton SM_Button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
