/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.OWSB.PURCHASE;

import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author cindy
 */
public class Purchase_PO extends javax.swing.JPanel {
    private javax.swing.JPanel ChangePanel;

    /**
     * Creates new form Purchase_PO
     */
    public Purchase_PO(javax.swing.JPanel ChangePanel, String itemName, String quantity, String supplierName, String purchaseManagerID, String deliveryDate) {
        this.ChangePanel = ChangePanel;
        initComponents();
        
        POID_TextField.setEditable(false);
        ItemID_TextField.setEditable(false);
        ItemName_TextField.setEditable(false);
        Quantity_TextField.setEditable(false);
        SupplierID_TextField.setEditable(false);
        Status_TextField.setEditable(false);
        EmpID_TextField.setEditable(false);
        Date_TextField.setEditable(false);
        
        ItemName_TextField.setText(itemName);
        Quantity_TextField.setText(quantity);
        Status_TextField.setText("Pending");
        Date_TextField.setText(deliveryDate);
        
        String itemID = getItemIDFromFile(itemName);
        ItemID_TextField.setText(itemID != null ? itemID : "Not Found");
        
        ItemName_TextField.setText(getItemNameFromID(itemID));
        
        SupplierID_TextField.setText(supplierName);
        
        
        String username = getUsernameFromEmpID(purchaseManagerID);
        if (username != null) {
            EmpID_TextField.setText(purchaseManagerID + " - " + username);
        } else {
            EmpID_TextField.setText(purchaseManagerID);
        }
        
        String newPOID = generateNextPOID();
        POID_TextField.setText(newPOID);
        
        savePOToFile(newPOID, itemID, itemName, quantity, supplierName, "Pending", purchaseManagerID, deliveryDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PO_Label = new javax.swing.JLabel();
        POID_Label = new javax.swing.JLabel();
        ItemID_Label = new javax.swing.JLabel();
        ItemName_Label = new javax.swing.JLabel();
        Quantity_Label = new javax.swing.JLabel();
        SupplierID_Label = new javax.swing.JLabel();
        Status_Label = new javax.swing.JLabel();
        EmpID_Label = new javax.swing.JLabel();
        Date_Label = new javax.swing.JLabel();
        POID_TextField = new javax.swing.JTextField();
        ItemID_TextField = new javax.swing.JTextField();
        ItemName_TextField = new javax.swing.JTextField();
        Quantity_TextField = new javax.swing.JTextField();
        SupplierID_TextField = new javax.swing.JTextField();
        Status_TextField = new javax.swing.JTextField();
        EmpID_TextField = new javax.swing.JTextField();
        Date_TextField = new javax.swing.JTextField();
        DoneButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        PO_Label.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        PO_Label.setText("Purchase Order");

        POID_Label.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        POID_Label.setText("PO ID:");

        ItemID_Label.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        ItemID_Label.setText("Item ID:");

        ItemName_Label.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        ItemName_Label.setText("Item Name:");

        Quantity_Label.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Quantity_Label.setText("Quantity:");

        SupplierID_Label.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        SupplierID_Label.setText("Supplier:");

        Status_Label.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Status_Label.setText("Status:");

        EmpID_Label.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        EmpID_Label.setText("Raised By:");

        Date_Label.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Date_Label.setText("Required Delivery Date:");

        POID_TextField.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        ItemID_TextField.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        ItemName_TextField.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        Quantity_TextField.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        SupplierID_TextField.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        SupplierID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierID_TextFieldActionPerformed(evt);
            }
        });

        Status_TextField.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        EmpID_TextField.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        Date_TextField.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        DoneButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        DoneButton.setText("Done");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(PO_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(POID_Label)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ItemID_Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemName_Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quantity_Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SupplierID_Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Status_Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Date_Label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpID_Label, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(POID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ItemID_TextField)
                                    .addComponent(ItemName_TextField)
                                    .addComponent(Quantity_TextField)
                                    .addComponent(SupplierID_TextField)
                                    .addComponent(Status_TextField)
                                    .addComponent(EmpID_TextField)
                                    .addComponent(Date_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PO_Label)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(POID_Label))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(POID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ItemID_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemName_Label)
                    .addComponent(ItemName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity_Label)
                    .addComponent(Quantity_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierID_Label)
                    .addComponent(SupplierID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Status_Label)
                    .addComponent(Status_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpID_Label)
                    .addComponent(EmpID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date_Label)
                    .addComponent(Date_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SupplierID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierID_TextFieldActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        // TODO add your handling code here:
        Purchase_POLists PM_POLists = new Purchase_POLists(ChangePanel);
        
        ChangePanel.removeAll();
        ChangePanel.setLayout(new BorderLayout());
        ChangePanel.add(PM_POLists, BorderLayout.CENTER);
        ChangePanel.revalidate();
        ChangePanel.repaint();
    }//GEN-LAST:event_DoneButtonActionPerformed

    private String getItemNameFromID(String itemID) {
        try (BufferedReader reader = new BufferedReader(new FileReader("database/Inventory.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(";");
                if (parts.length >= 2 && parts[0].equalsIgnoreCase(itemID.trim())) {
                    return parts[1];
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return "Unknown Item";
    }
    
    private String getItemIDFromFile(String itemName) {
        try (BufferedReader reader = new BufferedReader(new FileReader("database/Inventory.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(";");
                if (parts.length >= 2 && parts[1].equalsIgnoreCase(itemName.trim())) {
                    return parts[0];
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
    
    private String getUsernameFromEmpID(String empID) {
        try (BufferedReader reader = new BufferedReader(new FileReader("login.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 3 && parts[0].equalsIgnoreCase(empID.trim())) {
                    return parts[1]; // Assuming username is at index 1
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    private String generateNextPOID() {
        int max = 0;
        try (BufferedReader reader = new BufferedReader(new FileReader("PO_Lists.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(";");
                if (parts.length > 0 && parts[0].startsWith("PO")) {
                    int num = Integer.parseInt(parts[0].substring(2));
                    if (num > max) max = num;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return String.format("PO%03d", max + 1);
    }
 
    private void savePOToFile(String poID, String itemID, String itemName, String quantity,String supplierName, String status, String purchaseManagerID, String date) {
        String newPOEntry = String.join(";", poID, itemID, itemName, quantity, supplierName, status, purchaseManagerID, date);
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("PO_Lists.txt", true))) {
            writer.write(newPOEntry);
            writer.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date_Label;
    private javax.swing.JTextField Date_TextField;
    private javax.swing.JButton DoneButton;
    private javax.swing.JLabel EmpID_Label;
    private javax.swing.JTextField EmpID_TextField;
    private javax.swing.JLabel ItemID_Label;
    private javax.swing.JTextField ItemID_TextField;
    private javax.swing.JLabel ItemName_Label;
    private javax.swing.JTextField ItemName_TextField;
    private javax.swing.JLabel POID_Label;
    private javax.swing.JTextField POID_TextField;
    private javax.swing.JLabel PO_Label;
    private javax.swing.JLabel Quantity_Label;
    private javax.swing.JTextField Quantity_TextField;
    private javax.swing.JLabel Status_Label;
    private javax.swing.JTextField Status_TextField;
    private javax.swing.JLabel SupplierID_Label;
    private javax.swing.JTextField SupplierID_TextField;
    // End of variables declaration//GEN-END:variables
}
