/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.OWSB.PURCHASE;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cindy
 */
public class Purchase_SupplierLists extends javax.swing.JPanel {
    private javax.swing.JPanel ChangePanel;

    /**
     * Creates new form Purchase_SupplierLists
     */
    public Purchase_SupplierLists(javax.swing.JPanel ChangePanel) {
        this.ChangePanel = ChangePanel;
        initComponents();
        loadSupplierListFromFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        POList_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PO_Table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        POList_Label.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        POList_Label.setText("Supplier List");

        PO_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(PO_Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(POList_Label)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(POList_Label)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadSupplierListFromFile() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[] {
            "Supplier ID", "Supplier Name", "Contact Person", "Phone", "Email", "Address", "Item Supplied"
        });

        try (BufferedReader br = new BufferedReader(new FileReader("database/Supplier.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (!line.isEmpty()) {
                    String[] data = line.split(";");
                    if (data.length == 7) {
                        model.addRow(data);
                    } else {
                        System.out.println("Skipping malformed line: " + line);
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading Suppliers.txt: " + e.getMessage());
        }

        PO_Table.setModel(model);
        // Set font and row height
        PO_Table.setFont(new java.awt.Font("Georgia", java.awt.Font.PLAIN, 14)); // Font type and size
        PO_Table.setRowHeight(25); // Row height

        // Set column widths 
        PO_Table.getColumnModel().getColumn(0).setPreferredWidth(70);  // Supplier ID
        PO_Table.getColumnModel().getColumn(1).setPreferredWidth(100);  // Supplier Name
        PO_Table.getColumnModel().getColumn(2).setPreferredWidth(100); // Contact Person
        PO_Table.getColumnModel().getColumn(3).setPreferredWidth(80);  // Contact Number
        PO_Table.getColumnModel().getColumn(4).setPreferredWidth(90);  // Email
        PO_Table.getColumnModel().getColumn(5).setPreferredWidth(80);  // Address
        PO_Table.getColumnModel().getColumn(6).setPreferredWidth(120);  // Item Supplied

        PO_Table.getTableHeader().setFont(new java.awt.Font("Georgia", java.awt.Font.BOLD, 12));
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel POList_Label;
    private javax.swing.JTable PO_Table;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
